/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppVendorsRouteImport } from './routes/_app.vendors'
import { Route as AppUsersRouteImport } from './routes/_app.users'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppServicesRouteImport } from './routes/_app.services'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppProjectsRouteImport } from './routes/_app.projects'
import { Route as AppPluginsRouteImport } from './routes/_app.plugins'
import { Route as AppFundsRouteImport } from './routes/_app.funds'
import { Route as AppForecastRouteImport } from './routes/_app.forecast'
import { Route as AppVendorsIndexRouteImport } from './routes/_app.vendors.index'
import { Route as AppUsersIndexRouteImport } from './routes/_app.users.index'
import { Route as AppServicesIndexRouteImport } from './routes/_app.services.index'
import { Route as AppReportsIndexRouteImport } from './routes/_app.reports.index'
import { Route as AppProjectsIndexRouteImport } from './routes/_app.projects.index'
import { Route as AppFundsIndexRouteImport } from './routes/_app.funds.index'
import { Route as AppForecastIndexRouteImport } from './routes/_app.forecast.index'
import { Route as AppVendorsAddRouteImport } from './routes/_app.vendors.add'
import { Route as AppVendorsVendorIdRouteImport } from './routes/_app.vendors.$vendorId'
import { Route as AppUsersAddRouteImport } from './routes/_app.users.add'
import { Route as AppServicesAddRouteImport } from './routes/_app.services.add'
import { Route as AppProjectsNewRouteImport } from './routes/_app.projects.new'
import { Route as AppProjectsIdRouteImport } from './routes/_app.projects.$id'
import { Route as AppFundsAllocateRouteImport } from './routes/_app.funds.allocate'
import { Route as AppForecastAddRouteImport } from './routes/_app.forecast.add'
import { Route as AppVendorsVendorIdIndexRouteImport } from './routes/_app.vendors.$vendorId.index'
import { Route as AppProjectsIdIndexRouteImport } from './routes/_app.projects.$id.index'
import { Route as AppVendorsVendorIdEditRouteImport } from './routes/_app.vendors.$vendorId.edit'
import { Route as AppUsersUserIdEditRouteImport } from './routes/_app.users.$userId.edit'
import { Route as AppServicesServiceIdEditRouteImport } from './routes/_app.services.$serviceId.edit'
import { Route as AppProjectsIdTriggersRouteImport } from './routes/_app.projects.$id.triggers'
import { Route as AppProjectsIdTasksRouteImport } from './routes/_app.projects.$id.tasks'
import { Route as AppProjectsIdReportsRouteImport } from './routes/_app.projects.$id.reports'
import { Route as AppProjectsIdFundsRouteImport } from './routes/_app.projects.$id.funds'
import { Route as AppProjectsIdEditRouteImport } from './routes/_app.projects.$id.edit'
import { Route as AppProjectsIdBenefitsRouteImport } from './routes/_app.projects.$id.benefits'
import { Route as AppProjectsIdBeneficiariesRouteImport } from './routes/_app.projects.$id.beneficiaries'
import { Route as AppForecastSourceIdEditRouteImport } from './routes/_app.forecast.$sourceId.edit'
import { Route as AppProjectsIdTriggersIndexRouteImport } from './routes/_app.projects.$id.triggers.index'
import { Route as AppProjectsIdTasksIndexRouteImport } from './routes/_app.projects.$id.tasks.index'
import { Route as AppProjectsIdReportsIndexRouteImport } from './routes/_app.projects.$id.reports.index'
import { Route as AppProjectsIdFundsIndexRouteImport } from './routes/_app.projects.$id.funds.index'
import { Route as AppProjectsIdCommunicationIndexRouteImport } from './routes/_app.projects.$id.communication.index'
import { Route as AppProjectsIdBenefitsIndexRouteImport } from './routes/_app.projects.$id.benefits.index'
import { Route as AppProjectsIdBeneficiariesIndexRouteImport } from './routes/_app.projects.$id.beneficiaries.index'
import { Route as AppProjectsIdTriggersStatementIdRouteImport } from './routes/_app.projects.$id.triggers.$statementId'
import { Route as AppProjectsIdTasksAddTaskRouteImport } from './routes/_app.projects.$id.tasks.add-task'
import { Route as AppProjectsIdTasksTaskIdRouteImport } from './routes/_app.projects.$id.tasks.$taskId'
import { Route as AppProjectsIdCommunicationAddRouteImport } from './routes/_app.projects.$id.communication.add'
import { Route as AppProjectsIdCommunicationCampaignIdRouteImport } from './routes/_app.projects.$id.communication.$campaignId'
import { Route as AppProjectsIdBenefitsTokensRouteImport } from './routes/_app.projects.$id.benefits.tokens'
import { Route as AppProjectsIdBenefitsNewRouteImport } from './routes/_app.projects.$id.benefits.new'
import { Route as AppProjectsIdBenefitsAddRouteImport } from './routes/_app.projects.$id.benefits.add'
import { Route as AppProjectsIdBeneficiariesGroupsRouteImport } from './routes/_app.projects.$id.beneficiaries.groups'
import { Route as AppProjectsIdBeneficiariesAddRouteImport } from './routes/_app.projects.$id.beneficiaries.add'
import { Route as AppForecastSourceIdGlofasItemIndexRouteImport } from './routes/_app.forecast.$sourceId.glofas.$itemIndex'
import { Route as AppProjectsIdTriggersStatementIdIndexRouteImport } from './routes/_app.projects.$id.triggers.$statementId.index'
import { Route as AppProjectsIdTasksTaskIdIndexRouteImport } from './routes/_app.projects.$id.tasks.$taskId.index'
import { Route as AppProjectsIdBenefitsBenefitIdIndexRouteImport } from './routes/_app.projects.$id.benefits.$benefitId.index'
import { Route as AppProjectsIdTriggersStatementIdConfigureRouteImport } from './routes/_app.projects.$id.triggers.$statementId.configure'
import { Route as AppProjectsIdTriggersStatementIdAddRouteImport } from './routes/_app.projects.$id.triggers.$statementId.add'
import { Route as AppProjectsIdTasksTaskIdEditRouteImport } from './routes/_app.projects.$id.tasks.$taskId.edit'
import { Route as AppProjectsIdBenefitsBenefitIdEditRouteImport } from './routes/_app.projects.$id.benefits.$benefitId.edit'
import { Route as AppProjectsIdBeneficiariesBeneficiaryIdEditRouteImport } from './routes/_app.projects.$id.beneficiaries.$beneficiaryId.edit'
import { Route as AppProjectsIdBenefitsBenefitIdBeneficiariesAddRouteImport } from './routes/_app.projects.$id.benefits.$benefitId.beneficiaries.add'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppVendorsRoute = AppVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppServicesRoute = AppServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppPluginsRoute = AppPluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => AppRoute,
} as any)
const AppFundsRoute = AppFundsRouteImport.update({
  id: '/funds',
  path: '/funds',
  getParentRoute: () => AppRoute,
} as any)
const AppForecastRoute = AppForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => AppRoute,
} as any)
const AppVendorsIndexRoute = AppVendorsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppVendorsRoute,
} as any)
const AppUsersIndexRoute = AppUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppUsersRoute,
} as any)
const AppServicesIndexRoute = AppServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppServicesRoute,
} as any)
const AppReportsIndexRoute = AppReportsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppReportsRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProjectsRoute,
} as any)
const AppFundsIndexRoute = AppFundsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppFundsRoute,
} as any)
const AppForecastIndexRoute = AppForecastIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppForecastRoute,
} as any)
const AppVendorsAddRoute = AppVendorsAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => AppVendorsRoute,
} as any)
const AppVendorsVendorIdRoute = AppVendorsVendorIdRouteImport.update({
  id: '/$vendorId',
  path: '/$vendorId',
  getParentRoute: () => AppVendorsRoute,
} as any)
const AppUsersAddRoute = AppUsersAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => AppUsersRoute,
} as any)
const AppServicesAddRoute = AppServicesAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => AppServicesRoute,
} as any)
const AppProjectsNewRoute = AppProjectsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppProjectsRoute,
} as any)
const AppProjectsIdRoute = AppProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppProjectsRoute,
} as any)
const AppFundsAllocateRoute = AppFundsAllocateRouteImport.update({
  id: '/allocate',
  path: '/allocate',
  getParentRoute: () => AppFundsRoute,
} as any)
const AppForecastAddRoute = AppForecastAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => AppForecastRoute,
} as any)
const AppVendorsVendorIdIndexRoute = AppVendorsVendorIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppVendorsVendorIdRoute,
} as any)
const AppProjectsIdIndexRoute = AppProjectsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProjectsIdRoute,
} as any)
const AppVendorsVendorIdEditRoute = AppVendorsVendorIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppVendorsVendorIdRoute,
} as any)
const AppUsersUserIdEditRoute = AppUsersUserIdEditRouteImport.update({
  id: '/$userId/edit',
  path: '/$userId/edit',
  getParentRoute: () => AppUsersRoute,
} as any)
const AppServicesServiceIdEditRoute =
  AppServicesServiceIdEditRouteImport.update({
    id: '/$serviceId/edit',
    path: '/$serviceId/edit',
    getParentRoute: () => AppServicesRoute,
  } as any)
const AppProjectsIdTriggersRoute = AppProjectsIdTriggersRouteImport.update({
  id: '/triggers',
  path: '/triggers',
  getParentRoute: () => AppProjectsIdRoute,
} as any)
const AppProjectsIdTasksRoute = AppProjectsIdTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppProjectsIdRoute,
} as any)
const AppProjectsIdReportsRoute = AppProjectsIdReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppProjectsIdRoute,
} as any)
const AppProjectsIdFundsRoute = AppProjectsIdFundsRouteImport.update({
  id: '/funds',
  path: '/funds',
  getParentRoute: () => AppProjectsIdRoute,
} as any)
const AppProjectsIdEditRoute = AppProjectsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppProjectsIdRoute,
} as any)
const AppProjectsIdBenefitsRoute = AppProjectsIdBenefitsRouteImport.update({
  id: '/benefits',
  path: '/benefits',
  getParentRoute: () => AppProjectsIdRoute,
} as any)
const AppProjectsIdBeneficiariesRoute =
  AppProjectsIdBeneficiariesRouteImport.update({
    id: '/beneficiaries',
    path: '/beneficiaries',
    getParentRoute: () => AppProjectsIdRoute,
  } as any)
const AppForecastSourceIdEditRoute = AppForecastSourceIdEditRouteImport.update({
  id: '/$sourceId/edit',
  path: '/$sourceId/edit',
  getParentRoute: () => AppForecastRoute,
} as any)
const AppProjectsIdTriggersIndexRoute =
  AppProjectsIdTriggersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppProjectsIdTriggersRoute,
  } as any)
const AppProjectsIdTasksIndexRoute = AppProjectsIdTasksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProjectsIdTasksRoute,
} as any)
const AppProjectsIdReportsIndexRoute =
  AppProjectsIdReportsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppProjectsIdReportsRoute,
  } as any)
const AppProjectsIdFundsIndexRoute = AppProjectsIdFundsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProjectsIdFundsRoute,
} as any)
const AppProjectsIdCommunicationIndexRoute =
  AppProjectsIdCommunicationIndexRouteImport.update({
    id: '/communication/',
    path: '/communication/',
    getParentRoute: () => AppProjectsIdRoute,
  } as any)
const AppProjectsIdBenefitsIndexRoute =
  AppProjectsIdBenefitsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppProjectsIdBenefitsRoute,
  } as any)
const AppProjectsIdBeneficiariesIndexRoute =
  AppProjectsIdBeneficiariesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppProjectsIdBeneficiariesRoute,
  } as any)
const AppProjectsIdTriggersStatementIdRoute =
  AppProjectsIdTriggersStatementIdRouteImport.update({
    id: '/$statementId',
    path: '/$statementId',
    getParentRoute: () => AppProjectsIdTriggersRoute,
  } as any)
const AppProjectsIdTasksAddTaskRoute =
  AppProjectsIdTasksAddTaskRouteImport.update({
    id: '/add-task',
    path: '/add-task',
    getParentRoute: () => AppProjectsIdTasksRoute,
  } as any)
const AppProjectsIdTasksTaskIdRoute =
  AppProjectsIdTasksTaskIdRouteImport.update({
    id: '/$taskId',
    path: '/$taskId',
    getParentRoute: () => AppProjectsIdTasksRoute,
  } as any)
const AppProjectsIdCommunicationAddRoute =
  AppProjectsIdCommunicationAddRouteImport.update({
    id: '/communication/add',
    path: '/communication/add',
    getParentRoute: () => AppProjectsIdRoute,
  } as any)
const AppProjectsIdCommunicationCampaignIdRoute =
  AppProjectsIdCommunicationCampaignIdRouteImport.update({
    id: '/communication/$campaignId',
    path: '/communication/$campaignId',
    getParentRoute: () => AppProjectsIdRoute,
  } as any)
const AppProjectsIdBenefitsTokensRoute =
  AppProjectsIdBenefitsTokensRouteImport.update({
    id: '/tokens',
    path: '/tokens',
    getParentRoute: () => AppProjectsIdBenefitsRoute,
  } as any)
const AppProjectsIdBenefitsNewRoute =
  AppProjectsIdBenefitsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AppProjectsIdBenefitsRoute,
  } as any)
const AppProjectsIdBenefitsAddRoute =
  AppProjectsIdBenefitsAddRouteImport.update({
    id: '/add',
    path: '/add',
    getParentRoute: () => AppProjectsIdBenefitsRoute,
  } as any)
const AppProjectsIdBeneficiariesGroupsRoute =
  AppProjectsIdBeneficiariesGroupsRouteImport.update({
    id: '/groups',
    path: '/groups',
    getParentRoute: () => AppProjectsIdBeneficiariesRoute,
  } as any)
const AppProjectsIdBeneficiariesAddRoute =
  AppProjectsIdBeneficiariesAddRouteImport.update({
    id: '/add',
    path: '/add',
    getParentRoute: () => AppProjectsIdBeneficiariesRoute,
  } as any)
const AppForecastSourceIdGlofasItemIndexRoute =
  AppForecastSourceIdGlofasItemIndexRouteImport.update({
    id: '/$sourceId/glofas/$itemIndex',
    path: '/$sourceId/glofas/$itemIndex',
    getParentRoute: () => AppForecastRoute,
  } as any)
const AppProjectsIdTriggersStatementIdIndexRoute =
  AppProjectsIdTriggersStatementIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppProjectsIdTriggersStatementIdRoute,
  } as any)
const AppProjectsIdTasksTaskIdIndexRoute =
  AppProjectsIdTasksTaskIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppProjectsIdTasksTaskIdRoute,
  } as any)
const AppProjectsIdBenefitsBenefitIdIndexRoute =
  AppProjectsIdBenefitsBenefitIdIndexRouteImport.update({
    id: '/$benefitId/',
    path: '/$benefitId/',
    getParentRoute: () => AppProjectsIdBenefitsRoute,
  } as any)
const AppProjectsIdTriggersStatementIdConfigureRoute =
  AppProjectsIdTriggersStatementIdConfigureRouteImport.update({
    id: '/configure',
    path: '/configure',
    getParentRoute: () => AppProjectsIdTriggersStatementIdRoute,
  } as any)
const AppProjectsIdTriggersStatementIdAddRoute =
  AppProjectsIdTriggersStatementIdAddRouteImport.update({
    id: '/add',
    path: '/add',
    getParentRoute: () => AppProjectsIdTriggersStatementIdRoute,
  } as any)
const AppProjectsIdTasksTaskIdEditRoute =
  AppProjectsIdTasksTaskIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AppProjectsIdTasksTaskIdRoute,
  } as any)
const AppProjectsIdBenefitsBenefitIdEditRoute =
  AppProjectsIdBenefitsBenefitIdEditRouteImport.update({
    id: '/$benefitId/edit',
    path: '/$benefitId/edit',
    getParentRoute: () => AppProjectsIdBenefitsRoute,
  } as any)
const AppProjectsIdBeneficiariesBeneficiaryIdEditRoute =
  AppProjectsIdBeneficiariesBeneficiaryIdEditRouteImport.update({
    id: '/$beneficiaryId/edit',
    path: '/$beneficiaryId/edit',
    getParentRoute: () => AppProjectsIdBeneficiariesRoute,
  } as any)
const AppProjectsIdBenefitsBenefitIdBeneficiariesAddRoute =
  AppProjectsIdBenefitsBenefitIdBeneficiariesAddRouteImport.update({
    id: '/$benefitId/beneficiaries/add',
    path: '/$benefitId/beneficiaries/add',
    getParentRoute: () => AppProjectsIdBenefitsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/forecast': typeof AppForecastRouteWithChildren
  '/funds': typeof AppFundsRouteWithChildren
  '/plugins': typeof AppPluginsRoute
  '/projects': typeof AppProjectsRouteWithChildren
  '/reports': typeof AppReportsRouteWithChildren
  '/services': typeof AppServicesRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/users': typeof AppUsersRouteWithChildren
  '/vendors': typeof AppVendorsRouteWithChildren
  '/forecast/add': typeof AppForecastAddRoute
  '/funds/allocate': typeof AppFundsAllocateRoute
  '/projects/$id': typeof AppProjectsIdRouteWithChildren
  '/projects/new': typeof AppProjectsNewRoute
  '/services/add': typeof AppServicesAddRoute
  '/users/add': typeof AppUsersAddRoute
  '/vendors/$vendorId': typeof AppVendorsVendorIdRouteWithChildren
  '/vendors/add': typeof AppVendorsAddRoute
  '/forecast/': typeof AppForecastIndexRoute
  '/funds/': typeof AppFundsIndexRoute
  '/projects/': typeof AppProjectsIndexRoute
  '/reports/': typeof AppReportsIndexRoute
  '/services/': typeof AppServicesIndexRoute
  '/users/': typeof AppUsersIndexRoute
  '/vendors/': typeof AppVendorsIndexRoute
  '/forecast/$sourceId/edit': typeof AppForecastSourceIdEditRoute
  '/projects/$id/beneficiaries': typeof AppProjectsIdBeneficiariesRouteWithChildren
  '/projects/$id/benefits': typeof AppProjectsIdBenefitsRouteWithChildren
  '/projects/$id/edit': typeof AppProjectsIdEditRoute
  '/projects/$id/funds': typeof AppProjectsIdFundsRouteWithChildren
  '/projects/$id/reports': typeof AppProjectsIdReportsRouteWithChildren
  '/projects/$id/tasks': typeof AppProjectsIdTasksRouteWithChildren
  '/projects/$id/triggers': typeof AppProjectsIdTriggersRouteWithChildren
  '/services/$serviceId/edit': typeof AppServicesServiceIdEditRoute
  '/users/$userId/edit': typeof AppUsersUserIdEditRoute
  '/vendors/$vendorId/edit': typeof AppVendorsVendorIdEditRoute
  '/projects/$id/': typeof AppProjectsIdIndexRoute
  '/vendors/$vendorId/': typeof AppVendorsVendorIdIndexRoute
  '/forecast/$sourceId/glofas/$itemIndex': typeof AppForecastSourceIdGlofasItemIndexRoute
  '/projects/$id/beneficiaries/add': typeof AppProjectsIdBeneficiariesAddRoute
  '/projects/$id/beneficiaries/groups': typeof AppProjectsIdBeneficiariesGroupsRoute
  '/projects/$id/benefits/add': typeof AppProjectsIdBenefitsAddRoute
  '/projects/$id/benefits/new': typeof AppProjectsIdBenefitsNewRoute
  '/projects/$id/benefits/tokens': typeof AppProjectsIdBenefitsTokensRoute
  '/projects/$id/communication/$campaignId': typeof AppProjectsIdCommunicationCampaignIdRoute
  '/projects/$id/communication/add': typeof AppProjectsIdCommunicationAddRoute
  '/projects/$id/tasks/$taskId': typeof AppProjectsIdTasksTaskIdRouteWithChildren
  '/projects/$id/tasks/add-task': typeof AppProjectsIdTasksAddTaskRoute
  '/projects/$id/triggers/$statementId': typeof AppProjectsIdTriggersStatementIdRouteWithChildren
  '/projects/$id/beneficiaries/': typeof AppProjectsIdBeneficiariesIndexRoute
  '/projects/$id/benefits/': typeof AppProjectsIdBenefitsIndexRoute
  '/projects/$id/communication/': typeof AppProjectsIdCommunicationIndexRoute
  '/projects/$id/funds/': typeof AppProjectsIdFundsIndexRoute
  '/projects/$id/reports/': typeof AppProjectsIdReportsIndexRoute
  '/projects/$id/tasks/': typeof AppProjectsIdTasksIndexRoute
  '/projects/$id/triggers/': typeof AppProjectsIdTriggersIndexRoute
  '/projects/$id/beneficiaries/$beneficiaryId/edit': typeof AppProjectsIdBeneficiariesBeneficiaryIdEditRoute
  '/projects/$id/benefits/$benefitId/edit': typeof AppProjectsIdBenefitsBenefitIdEditRoute
  '/projects/$id/tasks/$taskId/edit': typeof AppProjectsIdTasksTaskIdEditRoute
  '/projects/$id/triggers/$statementId/add': typeof AppProjectsIdTriggersStatementIdAddRoute
  '/projects/$id/triggers/$statementId/configure': typeof AppProjectsIdTriggersStatementIdConfigureRoute
  '/projects/$id/benefits/$benefitId/': typeof AppProjectsIdBenefitsBenefitIdIndexRoute
  '/projects/$id/tasks/$taskId/': typeof AppProjectsIdTasksTaskIdIndexRoute
  '/projects/$id/triggers/$statementId/': typeof AppProjectsIdTriggersStatementIdIndexRoute
  '/projects/$id/benefits/$benefitId/beneficiaries/add': typeof AppProjectsIdBenefitsBenefitIdBeneficiariesAddRoute
}
export interface FileRoutesByTo {
  '/plugins': typeof AppPluginsRoute
  '/settings': typeof AppSettingsRoute
  '/': typeof AppIndexRoute
  '/forecast/add': typeof AppForecastAddRoute
  '/funds/allocate': typeof AppFundsAllocateRoute
  '/projects/new': typeof AppProjectsNewRoute
  '/services/add': typeof AppServicesAddRoute
  '/users/add': typeof AppUsersAddRoute
  '/vendors/add': typeof AppVendorsAddRoute
  '/forecast': typeof AppForecastIndexRoute
  '/funds': typeof AppFundsIndexRoute
  '/projects': typeof AppProjectsIndexRoute
  '/reports': typeof AppReportsIndexRoute
  '/services': typeof AppServicesIndexRoute
  '/users': typeof AppUsersIndexRoute
  '/vendors': typeof AppVendorsIndexRoute
  '/forecast/$sourceId/edit': typeof AppForecastSourceIdEditRoute
  '/projects/$id/edit': typeof AppProjectsIdEditRoute
  '/services/$serviceId/edit': typeof AppServicesServiceIdEditRoute
  '/users/$userId/edit': typeof AppUsersUserIdEditRoute
  '/vendors/$vendorId/edit': typeof AppVendorsVendorIdEditRoute
  '/projects/$id': typeof AppProjectsIdIndexRoute
  '/vendors/$vendorId': typeof AppVendorsVendorIdIndexRoute
  '/forecast/$sourceId/glofas/$itemIndex': typeof AppForecastSourceIdGlofasItemIndexRoute
  '/projects/$id/beneficiaries/add': typeof AppProjectsIdBeneficiariesAddRoute
  '/projects/$id/beneficiaries/groups': typeof AppProjectsIdBeneficiariesGroupsRoute
  '/projects/$id/benefits/add': typeof AppProjectsIdBenefitsAddRoute
  '/projects/$id/benefits/new': typeof AppProjectsIdBenefitsNewRoute
  '/projects/$id/benefits/tokens': typeof AppProjectsIdBenefitsTokensRoute
  '/projects/$id/communication/$campaignId': typeof AppProjectsIdCommunicationCampaignIdRoute
  '/projects/$id/communication/add': typeof AppProjectsIdCommunicationAddRoute
  '/projects/$id/tasks/add-task': typeof AppProjectsIdTasksAddTaskRoute
  '/projects/$id/beneficiaries': typeof AppProjectsIdBeneficiariesIndexRoute
  '/projects/$id/benefits': typeof AppProjectsIdBenefitsIndexRoute
  '/projects/$id/communication': typeof AppProjectsIdCommunicationIndexRoute
  '/projects/$id/funds': typeof AppProjectsIdFundsIndexRoute
  '/projects/$id/reports': typeof AppProjectsIdReportsIndexRoute
  '/projects/$id/tasks': typeof AppProjectsIdTasksIndexRoute
  '/projects/$id/triggers': typeof AppProjectsIdTriggersIndexRoute
  '/projects/$id/beneficiaries/$beneficiaryId/edit': typeof AppProjectsIdBeneficiariesBeneficiaryIdEditRoute
  '/projects/$id/benefits/$benefitId/edit': typeof AppProjectsIdBenefitsBenefitIdEditRoute
  '/projects/$id/tasks/$taskId/edit': typeof AppProjectsIdTasksTaskIdEditRoute
  '/projects/$id/triggers/$statementId/add': typeof AppProjectsIdTriggersStatementIdAddRoute
  '/projects/$id/triggers/$statementId/configure': typeof AppProjectsIdTriggersStatementIdConfigureRoute
  '/projects/$id/benefits/$benefitId': typeof AppProjectsIdBenefitsBenefitIdIndexRoute
  '/projects/$id/tasks/$taskId': typeof AppProjectsIdTasksTaskIdIndexRoute
  '/projects/$id/triggers/$statementId': typeof AppProjectsIdTriggersStatementIdIndexRoute
  '/projects/$id/benefits/$benefitId/beneficiaries/add': typeof AppProjectsIdBenefitsBenefitIdBeneficiariesAddRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/forecast': typeof AppForecastRouteWithChildren
  '/_app/funds': typeof AppFundsRouteWithChildren
  '/_app/plugins': typeof AppPluginsRoute
  '/_app/projects': typeof AppProjectsRouteWithChildren
  '/_app/reports': typeof AppReportsRouteWithChildren
  '/_app/services': typeof AppServicesRouteWithChildren
  '/_app/settings': typeof AppSettingsRoute
  '/_app/users': typeof AppUsersRouteWithChildren
  '/_app/vendors': typeof AppVendorsRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/forecast/add': typeof AppForecastAddRoute
  '/_app/funds/allocate': typeof AppFundsAllocateRoute
  '/_app/projects/$id': typeof AppProjectsIdRouteWithChildren
  '/_app/projects/new': typeof AppProjectsNewRoute
  '/_app/services/add': typeof AppServicesAddRoute
  '/_app/users/add': typeof AppUsersAddRoute
  '/_app/vendors/$vendorId': typeof AppVendorsVendorIdRouteWithChildren
  '/_app/vendors/add': typeof AppVendorsAddRoute
  '/_app/forecast/': typeof AppForecastIndexRoute
  '/_app/funds/': typeof AppFundsIndexRoute
  '/_app/projects/': typeof AppProjectsIndexRoute
  '/_app/reports/': typeof AppReportsIndexRoute
  '/_app/services/': typeof AppServicesIndexRoute
  '/_app/users/': typeof AppUsersIndexRoute
  '/_app/vendors/': typeof AppVendorsIndexRoute
  '/_app/forecast/$sourceId/edit': typeof AppForecastSourceIdEditRoute
  '/_app/projects/$id/beneficiaries': typeof AppProjectsIdBeneficiariesRouteWithChildren
  '/_app/projects/$id/benefits': typeof AppProjectsIdBenefitsRouteWithChildren
  '/_app/projects/$id/edit': typeof AppProjectsIdEditRoute
  '/_app/projects/$id/funds': typeof AppProjectsIdFundsRouteWithChildren
  '/_app/projects/$id/reports': typeof AppProjectsIdReportsRouteWithChildren
  '/_app/projects/$id/tasks': typeof AppProjectsIdTasksRouteWithChildren
  '/_app/projects/$id/triggers': typeof AppProjectsIdTriggersRouteWithChildren
  '/_app/services/$serviceId/edit': typeof AppServicesServiceIdEditRoute
  '/_app/users/$userId/edit': typeof AppUsersUserIdEditRoute
  '/_app/vendors/$vendorId/edit': typeof AppVendorsVendorIdEditRoute
  '/_app/projects/$id/': typeof AppProjectsIdIndexRoute
  '/_app/vendors/$vendorId/': typeof AppVendorsVendorIdIndexRoute
  '/_app/forecast/$sourceId/glofas/$itemIndex': typeof AppForecastSourceIdGlofasItemIndexRoute
  '/_app/projects/$id/beneficiaries/add': typeof AppProjectsIdBeneficiariesAddRoute
  '/_app/projects/$id/beneficiaries/groups': typeof AppProjectsIdBeneficiariesGroupsRoute
  '/_app/projects/$id/benefits/add': typeof AppProjectsIdBenefitsAddRoute
  '/_app/projects/$id/benefits/new': typeof AppProjectsIdBenefitsNewRoute
  '/_app/projects/$id/benefits/tokens': typeof AppProjectsIdBenefitsTokensRoute
  '/_app/projects/$id/communication/$campaignId': typeof AppProjectsIdCommunicationCampaignIdRoute
  '/_app/projects/$id/communication/add': typeof AppProjectsIdCommunicationAddRoute
  '/_app/projects/$id/tasks/$taskId': typeof AppProjectsIdTasksTaskIdRouteWithChildren
  '/_app/projects/$id/tasks/add-task': typeof AppProjectsIdTasksAddTaskRoute
  '/_app/projects/$id/triggers/$statementId': typeof AppProjectsIdTriggersStatementIdRouteWithChildren
  '/_app/projects/$id/beneficiaries/': typeof AppProjectsIdBeneficiariesIndexRoute
  '/_app/projects/$id/benefits/': typeof AppProjectsIdBenefitsIndexRoute
  '/_app/projects/$id/communication/': typeof AppProjectsIdCommunicationIndexRoute
  '/_app/projects/$id/funds/': typeof AppProjectsIdFundsIndexRoute
  '/_app/projects/$id/reports/': typeof AppProjectsIdReportsIndexRoute
  '/_app/projects/$id/tasks/': typeof AppProjectsIdTasksIndexRoute
  '/_app/projects/$id/triggers/': typeof AppProjectsIdTriggersIndexRoute
  '/_app/projects/$id/beneficiaries/$beneficiaryId/edit': typeof AppProjectsIdBeneficiariesBeneficiaryIdEditRoute
  '/_app/projects/$id/benefits/$benefitId/edit': typeof AppProjectsIdBenefitsBenefitIdEditRoute
  '/_app/projects/$id/tasks/$taskId/edit': typeof AppProjectsIdTasksTaskIdEditRoute
  '/_app/projects/$id/triggers/$statementId/add': typeof AppProjectsIdTriggersStatementIdAddRoute
  '/_app/projects/$id/triggers/$statementId/configure': typeof AppProjectsIdTriggersStatementIdConfigureRoute
  '/_app/projects/$id/benefits/$benefitId/': typeof AppProjectsIdBenefitsBenefitIdIndexRoute
  '/_app/projects/$id/tasks/$taskId/': typeof AppProjectsIdTasksTaskIdIndexRoute
  '/_app/projects/$id/triggers/$statementId/': typeof AppProjectsIdTriggersStatementIdIndexRoute
  '/_app/projects/$id/benefits/$benefitId/beneficiaries/add': typeof AppProjectsIdBenefitsBenefitIdBeneficiariesAddRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forecast'
    | '/funds'
    | '/plugins'
    | '/projects'
    | '/reports'
    | '/services'
    | '/settings'
    | '/users'
    | '/vendors'
    | '/forecast/add'
    | '/funds/allocate'
    | '/projects/$id'
    | '/projects/new'
    | '/services/add'
    | '/users/add'
    | '/vendors/$vendorId'
    | '/vendors/add'
    | '/forecast/'
    | '/funds/'
    | '/projects/'
    | '/reports/'
    | '/services/'
    | '/users/'
    | '/vendors/'
    | '/forecast/$sourceId/edit'
    | '/projects/$id/beneficiaries'
    | '/projects/$id/benefits'
    | '/projects/$id/edit'
    | '/projects/$id/funds'
    | '/projects/$id/reports'
    | '/projects/$id/tasks'
    | '/projects/$id/triggers'
    | '/services/$serviceId/edit'
    | '/users/$userId/edit'
    | '/vendors/$vendorId/edit'
    | '/projects/$id/'
    | '/vendors/$vendorId/'
    | '/forecast/$sourceId/glofas/$itemIndex'
    | '/projects/$id/beneficiaries/add'
    | '/projects/$id/beneficiaries/groups'
    | '/projects/$id/benefits/add'
    | '/projects/$id/benefits/new'
    | '/projects/$id/benefits/tokens'
    | '/projects/$id/communication/$campaignId'
    | '/projects/$id/communication/add'
    | '/projects/$id/tasks/$taskId'
    | '/projects/$id/tasks/add-task'
    | '/projects/$id/triggers/$statementId'
    | '/projects/$id/beneficiaries/'
    | '/projects/$id/benefits/'
    | '/projects/$id/communication/'
    | '/projects/$id/funds/'
    | '/projects/$id/reports/'
    | '/projects/$id/tasks/'
    | '/projects/$id/triggers/'
    | '/projects/$id/beneficiaries/$beneficiaryId/edit'
    | '/projects/$id/benefits/$benefitId/edit'
    | '/projects/$id/tasks/$taskId/edit'
    | '/projects/$id/triggers/$statementId/add'
    | '/projects/$id/triggers/$statementId/configure'
    | '/projects/$id/benefits/$benefitId/'
    | '/projects/$id/tasks/$taskId/'
    | '/projects/$id/triggers/$statementId/'
    | '/projects/$id/benefits/$benefitId/beneficiaries/add'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/plugins'
    | '/settings'
    | '/'
    | '/forecast/add'
    | '/funds/allocate'
    | '/projects/new'
    | '/services/add'
    | '/users/add'
    | '/vendors/add'
    | '/forecast'
    | '/funds'
    | '/projects'
    | '/reports'
    | '/services'
    | '/users'
    | '/vendors'
    | '/forecast/$sourceId/edit'
    | '/projects/$id/edit'
    | '/services/$serviceId/edit'
    | '/users/$userId/edit'
    | '/vendors/$vendorId/edit'
    | '/projects/$id'
    | '/vendors/$vendorId'
    | '/forecast/$sourceId/glofas/$itemIndex'
    | '/projects/$id/beneficiaries/add'
    | '/projects/$id/beneficiaries/groups'
    | '/projects/$id/benefits/add'
    | '/projects/$id/benefits/new'
    | '/projects/$id/benefits/tokens'
    | '/projects/$id/communication/$campaignId'
    | '/projects/$id/communication/add'
    | '/projects/$id/tasks/add-task'
    | '/projects/$id/beneficiaries'
    | '/projects/$id/benefits'
    | '/projects/$id/communication'
    | '/projects/$id/funds'
    | '/projects/$id/reports'
    | '/projects/$id/tasks'
    | '/projects/$id/triggers'
    | '/projects/$id/beneficiaries/$beneficiaryId/edit'
    | '/projects/$id/benefits/$benefitId/edit'
    | '/projects/$id/tasks/$taskId/edit'
    | '/projects/$id/triggers/$statementId/add'
    | '/projects/$id/triggers/$statementId/configure'
    | '/projects/$id/benefits/$benefitId'
    | '/projects/$id/tasks/$taskId'
    | '/projects/$id/triggers/$statementId'
    | '/projects/$id/benefits/$benefitId/beneficiaries/add'
  id:
    | '__root__'
    | '/_app'
    | '/_app/forecast'
    | '/_app/funds'
    | '/_app/plugins'
    | '/_app/projects'
    | '/_app/reports'
    | '/_app/services'
    | '/_app/settings'
    | '/_app/users'
    | '/_app/vendors'
    | '/_app/'
    | '/_app/forecast/add'
    | '/_app/funds/allocate'
    | '/_app/projects/$id'
    | '/_app/projects/new'
    | '/_app/services/add'
    | '/_app/users/add'
    | '/_app/vendors/$vendorId'
    | '/_app/vendors/add'
    | '/_app/forecast/'
    | '/_app/funds/'
    | '/_app/projects/'
    | '/_app/reports/'
    | '/_app/services/'
    | '/_app/users/'
    | '/_app/vendors/'
    | '/_app/forecast/$sourceId/edit'
    | '/_app/projects/$id/beneficiaries'
    | '/_app/projects/$id/benefits'
    | '/_app/projects/$id/edit'
    | '/_app/projects/$id/funds'
    | '/_app/projects/$id/reports'
    | '/_app/projects/$id/tasks'
    | '/_app/projects/$id/triggers'
    | '/_app/services/$serviceId/edit'
    | '/_app/users/$userId/edit'
    | '/_app/vendors/$vendorId/edit'
    | '/_app/projects/$id/'
    | '/_app/vendors/$vendorId/'
    | '/_app/forecast/$sourceId/glofas/$itemIndex'
    | '/_app/projects/$id/beneficiaries/add'
    | '/_app/projects/$id/beneficiaries/groups'
    | '/_app/projects/$id/benefits/add'
    | '/_app/projects/$id/benefits/new'
    | '/_app/projects/$id/benefits/tokens'
    | '/_app/projects/$id/communication/$campaignId'
    | '/_app/projects/$id/communication/add'
    | '/_app/projects/$id/tasks/$taskId'
    | '/_app/projects/$id/tasks/add-task'
    | '/_app/projects/$id/triggers/$statementId'
    | '/_app/projects/$id/beneficiaries/'
    | '/_app/projects/$id/benefits/'
    | '/_app/projects/$id/communication/'
    | '/_app/projects/$id/funds/'
    | '/_app/projects/$id/reports/'
    | '/_app/projects/$id/tasks/'
    | '/_app/projects/$id/triggers/'
    | '/_app/projects/$id/beneficiaries/$beneficiaryId/edit'
    | '/_app/projects/$id/benefits/$benefitId/edit'
    | '/_app/projects/$id/tasks/$taskId/edit'
    | '/_app/projects/$id/triggers/$statementId/add'
    | '/_app/projects/$id/triggers/$statementId/configure'
    | '/_app/projects/$id/benefits/$benefitId/'
    | '/_app/projects/$id/tasks/$taskId/'
    | '/_app/projects/$id/triggers/$statementId/'
    | '/_app/projects/$id/benefits/$benefitId/beneficiaries/add'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vendors': {
      id: '/_app/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof AppVendorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/services': {
      id: '/_app/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof AppServicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects': {
      id: '/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/plugins': {
      id: '/_app/plugins'
      path: '/plugins'
      fullPath: '/plugins'
      preLoaderRoute: typeof AppPluginsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/funds': {
      id: '/_app/funds'
      path: '/funds'
      fullPath: '/funds'
      preLoaderRoute: typeof AppFundsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/forecast': {
      id: '/_app/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof AppForecastRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vendors/': {
      id: '/_app/vendors/'
      path: '/'
      fullPath: '/vendors/'
      preLoaderRoute: typeof AppVendorsIndexRouteImport
      parentRoute: typeof AppVendorsRoute
    }
    '/_app/users/': {
      id: '/_app/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof AppUsersIndexRouteImport
      parentRoute: typeof AppUsersRoute
    }
    '/_app/services/': {
      id: '/_app/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof AppServicesIndexRouteImport
      parentRoute: typeof AppServicesRoute
    }
    '/_app/reports/': {
      id: '/_app/reports/'
      path: '/'
      fullPath: '/reports/'
      preLoaderRoute: typeof AppReportsIndexRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/_app/projects/': {
      id: '/_app/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/_app/funds/': {
      id: '/_app/funds/'
      path: '/'
      fullPath: '/funds/'
      preLoaderRoute: typeof AppFundsIndexRouteImport
      parentRoute: typeof AppFundsRoute
    }
    '/_app/forecast/': {
      id: '/_app/forecast/'
      path: '/'
      fullPath: '/forecast/'
      preLoaderRoute: typeof AppForecastIndexRouteImport
      parentRoute: typeof AppForecastRoute
    }
    '/_app/vendors/add': {
      id: '/_app/vendors/add'
      path: '/add'
      fullPath: '/vendors/add'
      preLoaderRoute: typeof AppVendorsAddRouteImport
      parentRoute: typeof AppVendorsRoute
    }
    '/_app/vendors/$vendorId': {
      id: '/_app/vendors/$vendorId'
      path: '/$vendorId'
      fullPath: '/vendors/$vendorId'
      preLoaderRoute: typeof AppVendorsVendorIdRouteImport
      parentRoute: typeof AppVendorsRoute
    }
    '/_app/users/add': {
      id: '/_app/users/add'
      path: '/add'
      fullPath: '/users/add'
      preLoaderRoute: typeof AppUsersAddRouteImport
      parentRoute: typeof AppUsersRoute
    }
    '/_app/services/add': {
      id: '/_app/services/add'
      path: '/add'
      fullPath: '/services/add'
      preLoaderRoute: typeof AppServicesAddRouteImport
      parentRoute: typeof AppServicesRoute
    }
    '/_app/projects/new': {
      id: '/_app/projects/new'
      path: '/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof AppProjectsNewRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/_app/projects/$id': {
      id: '/_app/projects/$id'
      path: '/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof AppProjectsIdRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/_app/funds/allocate': {
      id: '/_app/funds/allocate'
      path: '/allocate'
      fullPath: '/funds/allocate'
      preLoaderRoute: typeof AppFundsAllocateRouteImport
      parentRoute: typeof AppFundsRoute
    }
    '/_app/forecast/add': {
      id: '/_app/forecast/add'
      path: '/add'
      fullPath: '/forecast/add'
      preLoaderRoute: typeof AppForecastAddRouteImport
      parentRoute: typeof AppForecastRoute
    }
    '/_app/vendors/$vendorId/': {
      id: '/_app/vendors/$vendorId/'
      path: '/'
      fullPath: '/vendors/$vendorId/'
      preLoaderRoute: typeof AppVendorsVendorIdIndexRouteImport
      parentRoute: typeof AppVendorsVendorIdRoute
    }
    '/_app/projects/$id/': {
      id: '/_app/projects/$id/'
      path: '/'
      fullPath: '/projects/$id/'
      preLoaderRoute: typeof AppProjectsIdIndexRouteImport
      parentRoute: typeof AppProjectsIdRoute
    }
    '/_app/vendors/$vendorId/edit': {
      id: '/_app/vendors/$vendorId/edit'
      path: '/edit'
      fullPath: '/vendors/$vendorId/edit'
      preLoaderRoute: typeof AppVendorsVendorIdEditRouteImport
      parentRoute: typeof AppVendorsVendorIdRoute
    }
    '/_app/users/$userId/edit': {
      id: '/_app/users/$userId/edit'
      path: '/$userId/edit'
      fullPath: '/users/$userId/edit'
      preLoaderRoute: typeof AppUsersUserIdEditRouteImport
      parentRoute: typeof AppUsersRoute
    }
    '/_app/services/$serviceId/edit': {
      id: '/_app/services/$serviceId/edit'
      path: '/$serviceId/edit'
      fullPath: '/services/$serviceId/edit'
      preLoaderRoute: typeof AppServicesServiceIdEditRouteImport
      parentRoute: typeof AppServicesRoute
    }
    '/_app/projects/$id/triggers': {
      id: '/_app/projects/$id/triggers'
      path: '/triggers'
      fullPath: '/projects/$id/triggers'
      preLoaderRoute: typeof AppProjectsIdTriggersRouteImport
      parentRoute: typeof AppProjectsIdRoute
    }
    '/_app/projects/$id/tasks': {
      id: '/_app/projects/$id/tasks'
      path: '/tasks'
      fullPath: '/projects/$id/tasks'
      preLoaderRoute: typeof AppProjectsIdTasksRouteImport
      parentRoute: typeof AppProjectsIdRoute
    }
    '/_app/projects/$id/reports': {
      id: '/_app/projects/$id/reports'
      path: '/reports'
      fullPath: '/projects/$id/reports'
      preLoaderRoute: typeof AppProjectsIdReportsRouteImport
      parentRoute: typeof AppProjectsIdRoute
    }
    '/_app/projects/$id/funds': {
      id: '/_app/projects/$id/funds'
      path: '/funds'
      fullPath: '/projects/$id/funds'
      preLoaderRoute: typeof AppProjectsIdFundsRouteImport
      parentRoute: typeof AppProjectsIdRoute
    }
    '/_app/projects/$id/edit': {
      id: '/_app/projects/$id/edit'
      path: '/edit'
      fullPath: '/projects/$id/edit'
      preLoaderRoute: typeof AppProjectsIdEditRouteImport
      parentRoute: typeof AppProjectsIdRoute
    }
    '/_app/projects/$id/benefits': {
      id: '/_app/projects/$id/benefits'
      path: '/benefits'
      fullPath: '/projects/$id/benefits'
      preLoaderRoute: typeof AppProjectsIdBenefitsRouteImport
      parentRoute: typeof AppProjectsIdRoute
    }
    '/_app/projects/$id/beneficiaries': {
      id: '/_app/projects/$id/beneficiaries'
      path: '/beneficiaries'
      fullPath: '/projects/$id/beneficiaries'
      preLoaderRoute: typeof AppProjectsIdBeneficiariesRouteImport
      parentRoute: typeof AppProjectsIdRoute
    }
    '/_app/forecast/$sourceId/edit': {
      id: '/_app/forecast/$sourceId/edit'
      path: '/$sourceId/edit'
      fullPath: '/forecast/$sourceId/edit'
      preLoaderRoute: typeof AppForecastSourceIdEditRouteImport
      parentRoute: typeof AppForecastRoute
    }
    '/_app/projects/$id/triggers/': {
      id: '/_app/projects/$id/triggers/'
      path: '/'
      fullPath: '/projects/$id/triggers/'
      preLoaderRoute: typeof AppProjectsIdTriggersIndexRouteImport
      parentRoute: typeof AppProjectsIdTriggersRoute
    }
    '/_app/projects/$id/tasks/': {
      id: '/_app/projects/$id/tasks/'
      path: '/'
      fullPath: '/projects/$id/tasks/'
      preLoaderRoute: typeof AppProjectsIdTasksIndexRouteImport
      parentRoute: typeof AppProjectsIdTasksRoute
    }
    '/_app/projects/$id/reports/': {
      id: '/_app/projects/$id/reports/'
      path: '/'
      fullPath: '/projects/$id/reports/'
      preLoaderRoute: typeof AppProjectsIdReportsIndexRouteImport
      parentRoute: typeof AppProjectsIdReportsRoute
    }
    '/_app/projects/$id/funds/': {
      id: '/_app/projects/$id/funds/'
      path: '/'
      fullPath: '/projects/$id/funds/'
      preLoaderRoute: typeof AppProjectsIdFundsIndexRouteImport
      parentRoute: typeof AppProjectsIdFundsRoute
    }
    '/_app/projects/$id/communication/': {
      id: '/_app/projects/$id/communication/'
      path: '/communication'
      fullPath: '/projects/$id/communication/'
      preLoaderRoute: typeof AppProjectsIdCommunicationIndexRouteImport
      parentRoute: typeof AppProjectsIdRoute
    }
    '/_app/projects/$id/benefits/': {
      id: '/_app/projects/$id/benefits/'
      path: '/'
      fullPath: '/projects/$id/benefits/'
      preLoaderRoute: typeof AppProjectsIdBenefitsIndexRouteImport
      parentRoute: typeof AppProjectsIdBenefitsRoute
    }
    '/_app/projects/$id/beneficiaries/': {
      id: '/_app/projects/$id/beneficiaries/'
      path: '/'
      fullPath: '/projects/$id/beneficiaries/'
      preLoaderRoute: typeof AppProjectsIdBeneficiariesIndexRouteImport
      parentRoute: typeof AppProjectsIdBeneficiariesRoute
    }
    '/_app/projects/$id/triggers/$statementId': {
      id: '/_app/projects/$id/triggers/$statementId'
      path: '/$statementId'
      fullPath: '/projects/$id/triggers/$statementId'
      preLoaderRoute: typeof AppProjectsIdTriggersStatementIdRouteImport
      parentRoute: typeof AppProjectsIdTriggersRoute
    }
    '/_app/projects/$id/tasks/add-task': {
      id: '/_app/projects/$id/tasks/add-task'
      path: '/add-task'
      fullPath: '/projects/$id/tasks/add-task'
      preLoaderRoute: typeof AppProjectsIdTasksAddTaskRouteImport
      parentRoute: typeof AppProjectsIdTasksRoute
    }
    '/_app/projects/$id/tasks/$taskId': {
      id: '/_app/projects/$id/tasks/$taskId'
      path: '/$taskId'
      fullPath: '/projects/$id/tasks/$taskId'
      preLoaderRoute: typeof AppProjectsIdTasksTaskIdRouteImport
      parentRoute: typeof AppProjectsIdTasksRoute
    }
    '/_app/projects/$id/communication/add': {
      id: '/_app/projects/$id/communication/add'
      path: '/communication/add'
      fullPath: '/projects/$id/communication/add'
      preLoaderRoute: typeof AppProjectsIdCommunicationAddRouteImport
      parentRoute: typeof AppProjectsIdRoute
    }
    '/_app/projects/$id/communication/$campaignId': {
      id: '/_app/projects/$id/communication/$campaignId'
      path: '/communication/$campaignId'
      fullPath: '/projects/$id/communication/$campaignId'
      preLoaderRoute: typeof AppProjectsIdCommunicationCampaignIdRouteImport
      parentRoute: typeof AppProjectsIdRoute
    }
    '/_app/projects/$id/benefits/tokens': {
      id: '/_app/projects/$id/benefits/tokens'
      path: '/tokens'
      fullPath: '/projects/$id/benefits/tokens'
      preLoaderRoute: typeof AppProjectsIdBenefitsTokensRouteImport
      parentRoute: typeof AppProjectsIdBenefitsRoute
    }
    '/_app/projects/$id/benefits/new': {
      id: '/_app/projects/$id/benefits/new'
      path: '/new'
      fullPath: '/projects/$id/benefits/new'
      preLoaderRoute: typeof AppProjectsIdBenefitsNewRouteImport
      parentRoute: typeof AppProjectsIdBenefitsRoute
    }
    '/_app/projects/$id/benefits/add': {
      id: '/_app/projects/$id/benefits/add'
      path: '/add'
      fullPath: '/projects/$id/benefits/add'
      preLoaderRoute: typeof AppProjectsIdBenefitsAddRouteImport
      parentRoute: typeof AppProjectsIdBenefitsRoute
    }
    '/_app/projects/$id/beneficiaries/groups': {
      id: '/_app/projects/$id/beneficiaries/groups'
      path: '/groups'
      fullPath: '/projects/$id/beneficiaries/groups'
      preLoaderRoute: typeof AppProjectsIdBeneficiariesGroupsRouteImport
      parentRoute: typeof AppProjectsIdBeneficiariesRoute
    }
    '/_app/projects/$id/beneficiaries/add': {
      id: '/_app/projects/$id/beneficiaries/add'
      path: '/add'
      fullPath: '/projects/$id/beneficiaries/add'
      preLoaderRoute: typeof AppProjectsIdBeneficiariesAddRouteImport
      parentRoute: typeof AppProjectsIdBeneficiariesRoute
    }
    '/_app/forecast/$sourceId/glofas/$itemIndex': {
      id: '/_app/forecast/$sourceId/glofas/$itemIndex'
      path: '/$sourceId/glofas/$itemIndex'
      fullPath: '/forecast/$sourceId/glofas/$itemIndex'
      preLoaderRoute: typeof AppForecastSourceIdGlofasItemIndexRouteImport
      parentRoute: typeof AppForecastRoute
    }
    '/_app/projects/$id/triggers/$statementId/': {
      id: '/_app/projects/$id/triggers/$statementId/'
      path: '/'
      fullPath: '/projects/$id/triggers/$statementId/'
      preLoaderRoute: typeof AppProjectsIdTriggersStatementIdIndexRouteImport
      parentRoute: typeof AppProjectsIdTriggersStatementIdRoute
    }
    '/_app/projects/$id/tasks/$taskId/': {
      id: '/_app/projects/$id/tasks/$taskId/'
      path: '/'
      fullPath: '/projects/$id/tasks/$taskId/'
      preLoaderRoute: typeof AppProjectsIdTasksTaskIdIndexRouteImport
      parentRoute: typeof AppProjectsIdTasksTaskIdRoute
    }
    '/_app/projects/$id/benefits/$benefitId/': {
      id: '/_app/projects/$id/benefits/$benefitId/'
      path: '/$benefitId'
      fullPath: '/projects/$id/benefits/$benefitId/'
      preLoaderRoute: typeof AppProjectsIdBenefitsBenefitIdIndexRouteImport
      parentRoute: typeof AppProjectsIdBenefitsRoute
    }
    '/_app/projects/$id/triggers/$statementId/configure': {
      id: '/_app/projects/$id/triggers/$statementId/configure'
      path: '/configure'
      fullPath: '/projects/$id/triggers/$statementId/configure'
      preLoaderRoute: typeof AppProjectsIdTriggersStatementIdConfigureRouteImport
      parentRoute: typeof AppProjectsIdTriggersStatementIdRoute
    }
    '/_app/projects/$id/triggers/$statementId/add': {
      id: '/_app/projects/$id/triggers/$statementId/add'
      path: '/add'
      fullPath: '/projects/$id/triggers/$statementId/add'
      preLoaderRoute: typeof AppProjectsIdTriggersStatementIdAddRouteImport
      parentRoute: typeof AppProjectsIdTriggersStatementIdRoute
    }
    '/_app/projects/$id/tasks/$taskId/edit': {
      id: '/_app/projects/$id/tasks/$taskId/edit'
      path: '/edit'
      fullPath: '/projects/$id/tasks/$taskId/edit'
      preLoaderRoute: typeof AppProjectsIdTasksTaskIdEditRouteImport
      parentRoute: typeof AppProjectsIdTasksTaskIdRoute
    }
    '/_app/projects/$id/benefits/$benefitId/edit': {
      id: '/_app/projects/$id/benefits/$benefitId/edit'
      path: '/$benefitId/edit'
      fullPath: '/projects/$id/benefits/$benefitId/edit'
      preLoaderRoute: typeof AppProjectsIdBenefitsBenefitIdEditRouteImport
      parentRoute: typeof AppProjectsIdBenefitsRoute
    }
    '/_app/projects/$id/beneficiaries/$beneficiaryId/edit': {
      id: '/_app/projects/$id/beneficiaries/$beneficiaryId/edit'
      path: '/$beneficiaryId/edit'
      fullPath: '/projects/$id/beneficiaries/$beneficiaryId/edit'
      preLoaderRoute: typeof AppProjectsIdBeneficiariesBeneficiaryIdEditRouteImport
      parentRoute: typeof AppProjectsIdBeneficiariesRoute
    }
    '/_app/projects/$id/benefits/$benefitId/beneficiaries/add': {
      id: '/_app/projects/$id/benefits/$benefitId/beneficiaries/add'
      path: '/$benefitId/beneficiaries/add'
      fullPath: '/projects/$id/benefits/$benefitId/beneficiaries/add'
      preLoaderRoute: typeof AppProjectsIdBenefitsBenefitIdBeneficiariesAddRouteImport
      parentRoute: typeof AppProjectsIdBenefitsRoute
    }
  }
}

interface AppForecastRouteChildren {
  AppForecastAddRoute: typeof AppForecastAddRoute
  AppForecastIndexRoute: typeof AppForecastIndexRoute
  AppForecastSourceIdEditRoute: typeof AppForecastSourceIdEditRoute
  AppForecastSourceIdGlofasItemIndexRoute: typeof AppForecastSourceIdGlofasItemIndexRoute
}

const AppForecastRouteChildren: AppForecastRouteChildren = {
  AppForecastAddRoute: AppForecastAddRoute,
  AppForecastIndexRoute: AppForecastIndexRoute,
  AppForecastSourceIdEditRoute: AppForecastSourceIdEditRoute,
  AppForecastSourceIdGlofasItemIndexRoute:
    AppForecastSourceIdGlofasItemIndexRoute,
}

const AppForecastRouteWithChildren = AppForecastRoute._addFileChildren(
  AppForecastRouteChildren,
)

interface AppFundsRouteChildren {
  AppFundsAllocateRoute: typeof AppFundsAllocateRoute
  AppFundsIndexRoute: typeof AppFundsIndexRoute
}

const AppFundsRouteChildren: AppFundsRouteChildren = {
  AppFundsAllocateRoute: AppFundsAllocateRoute,
  AppFundsIndexRoute: AppFundsIndexRoute,
}

const AppFundsRouteWithChildren = AppFundsRoute._addFileChildren(
  AppFundsRouteChildren,
)

interface AppProjectsIdBeneficiariesRouteChildren {
  AppProjectsIdBeneficiariesAddRoute: typeof AppProjectsIdBeneficiariesAddRoute
  AppProjectsIdBeneficiariesGroupsRoute: typeof AppProjectsIdBeneficiariesGroupsRoute
  AppProjectsIdBeneficiariesIndexRoute: typeof AppProjectsIdBeneficiariesIndexRoute
  AppProjectsIdBeneficiariesBeneficiaryIdEditRoute: typeof AppProjectsIdBeneficiariesBeneficiaryIdEditRoute
}

const AppProjectsIdBeneficiariesRouteChildren: AppProjectsIdBeneficiariesRouteChildren =
  {
    AppProjectsIdBeneficiariesAddRoute: AppProjectsIdBeneficiariesAddRoute,
    AppProjectsIdBeneficiariesGroupsRoute:
      AppProjectsIdBeneficiariesGroupsRoute,
    AppProjectsIdBeneficiariesIndexRoute: AppProjectsIdBeneficiariesIndexRoute,
    AppProjectsIdBeneficiariesBeneficiaryIdEditRoute:
      AppProjectsIdBeneficiariesBeneficiaryIdEditRoute,
  }

const AppProjectsIdBeneficiariesRouteWithChildren =
  AppProjectsIdBeneficiariesRoute._addFileChildren(
    AppProjectsIdBeneficiariesRouteChildren,
  )

interface AppProjectsIdBenefitsRouteChildren {
  AppProjectsIdBenefitsAddRoute: typeof AppProjectsIdBenefitsAddRoute
  AppProjectsIdBenefitsNewRoute: typeof AppProjectsIdBenefitsNewRoute
  AppProjectsIdBenefitsTokensRoute: typeof AppProjectsIdBenefitsTokensRoute
  AppProjectsIdBenefitsIndexRoute: typeof AppProjectsIdBenefitsIndexRoute
  AppProjectsIdBenefitsBenefitIdEditRoute: typeof AppProjectsIdBenefitsBenefitIdEditRoute
  AppProjectsIdBenefitsBenefitIdIndexRoute: typeof AppProjectsIdBenefitsBenefitIdIndexRoute
  AppProjectsIdBenefitsBenefitIdBeneficiariesAddRoute: typeof AppProjectsIdBenefitsBenefitIdBeneficiariesAddRoute
}

const AppProjectsIdBenefitsRouteChildren: AppProjectsIdBenefitsRouteChildren = {
  AppProjectsIdBenefitsAddRoute: AppProjectsIdBenefitsAddRoute,
  AppProjectsIdBenefitsNewRoute: AppProjectsIdBenefitsNewRoute,
  AppProjectsIdBenefitsTokensRoute: AppProjectsIdBenefitsTokensRoute,
  AppProjectsIdBenefitsIndexRoute: AppProjectsIdBenefitsIndexRoute,
  AppProjectsIdBenefitsBenefitIdEditRoute:
    AppProjectsIdBenefitsBenefitIdEditRoute,
  AppProjectsIdBenefitsBenefitIdIndexRoute:
    AppProjectsIdBenefitsBenefitIdIndexRoute,
  AppProjectsIdBenefitsBenefitIdBeneficiariesAddRoute:
    AppProjectsIdBenefitsBenefitIdBeneficiariesAddRoute,
}

const AppProjectsIdBenefitsRouteWithChildren =
  AppProjectsIdBenefitsRoute._addFileChildren(
    AppProjectsIdBenefitsRouteChildren,
  )

interface AppProjectsIdFundsRouteChildren {
  AppProjectsIdFundsIndexRoute: typeof AppProjectsIdFundsIndexRoute
}

const AppProjectsIdFundsRouteChildren: AppProjectsIdFundsRouteChildren = {
  AppProjectsIdFundsIndexRoute: AppProjectsIdFundsIndexRoute,
}

const AppProjectsIdFundsRouteWithChildren =
  AppProjectsIdFundsRoute._addFileChildren(AppProjectsIdFundsRouteChildren)

interface AppProjectsIdReportsRouteChildren {
  AppProjectsIdReportsIndexRoute: typeof AppProjectsIdReportsIndexRoute
}

const AppProjectsIdReportsRouteChildren: AppProjectsIdReportsRouteChildren = {
  AppProjectsIdReportsIndexRoute: AppProjectsIdReportsIndexRoute,
}

const AppProjectsIdReportsRouteWithChildren =
  AppProjectsIdReportsRoute._addFileChildren(AppProjectsIdReportsRouteChildren)

interface AppProjectsIdTasksTaskIdRouteChildren {
  AppProjectsIdTasksTaskIdEditRoute: typeof AppProjectsIdTasksTaskIdEditRoute
  AppProjectsIdTasksTaskIdIndexRoute: typeof AppProjectsIdTasksTaskIdIndexRoute
}

const AppProjectsIdTasksTaskIdRouteChildren: AppProjectsIdTasksTaskIdRouteChildren =
  {
    AppProjectsIdTasksTaskIdEditRoute: AppProjectsIdTasksTaskIdEditRoute,
    AppProjectsIdTasksTaskIdIndexRoute: AppProjectsIdTasksTaskIdIndexRoute,
  }

const AppProjectsIdTasksTaskIdRouteWithChildren =
  AppProjectsIdTasksTaskIdRoute._addFileChildren(
    AppProjectsIdTasksTaskIdRouteChildren,
  )

interface AppProjectsIdTasksRouteChildren {
  AppProjectsIdTasksTaskIdRoute: typeof AppProjectsIdTasksTaskIdRouteWithChildren
  AppProjectsIdTasksAddTaskRoute: typeof AppProjectsIdTasksAddTaskRoute
  AppProjectsIdTasksIndexRoute: typeof AppProjectsIdTasksIndexRoute
}

const AppProjectsIdTasksRouteChildren: AppProjectsIdTasksRouteChildren = {
  AppProjectsIdTasksTaskIdRoute: AppProjectsIdTasksTaskIdRouteWithChildren,
  AppProjectsIdTasksAddTaskRoute: AppProjectsIdTasksAddTaskRoute,
  AppProjectsIdTasksIndexRoute: AppProjectsIdTasksIndexRoute,
}

const AppProjectsIdTasksRouteWithChildren =
  AppProjectsIdTasksRoute._addFileChildren(AppProjectsIdTasksRouteChildren)

interface AppProjectsIdTriggersStatementIdRouteChildren {
  AppProjectsIdTriggersStatementIdAddRoute: typeof AppProjectsIdTriggersStatementIdAddRoute
  AppProjectsIdTriggersStatementIdConfigureRoute: typeof AppProjectsIdTriggersStatementIdConfigureRoute
  AppProjectsIdTriggersStatementIdIndexRoute: typeof AppProjectsIdTriggersStatementIdIndexRoute
}

const AppProjectsIdTriggersStatementIdRouteChildren: AppProjectsIdTriggersStatementIdRouteChildren =
  {
    AppProjectsIdTriggersStatementIdAddRoute:
      AppProjectsIdTriggersStatementIdAddRoute,
    AppProjectsIdTriggersStatementIdConfigureRoute:
      AppProjectsIdTriggersStatementIdConfigureRoute,
    AppProjectsIdTriggersStatementIdIndexRoute:
      AppProjectsIdTriggersStatementIdIndexRoute,
  }

const AppProjectsIdTriggersStatementIdRouteWithChildren =
  AppProjectsIdTriggersStatementIdRoute._addFileChildren(
    AppProjectsIdTriggersStatementIdRouteChildren,
  )

interface AppProjectsIdTriggersRouteChildren {
  AppProjectsIdTriggersStatementIdRoute: typeof AppProjectsIdTriggersStatementIdRouteWithChildren
  AppProjectsIdTriggersIndexRoute: typeof AppProjectsIdTriggersIndexRoute
}

const AppProjectsIdTriggersRouteChildren: AppProjectsIdTriggersRouteChildren = {
  AppProjectsIdTriggersStatementIdRoute:
    AppProjectsIdTriggersStatementIdRouteWithChildren,
  AppProjectsIdTriggersIndexRoute: AppProjectsIdTriggersIndexRoute,
}

const AppProjectsIdTriggersRouteWithChildren =
  AppProjectsIdTriggersRoute._addFileChildren(
    AppProjectsIdTriggersRouteChildren,
  )

interface AppProjectsIdRouteChildren {
  AppProjectsIdBeneficiariesRoute: typeof AppProjectsIdBeneficiariesRouteWithChildren
  AppProjectsIdBenefitsRoute: typeof AppProjectsIdBenefitsRouteWithChildren
  AppProjectsIdEditRoute: typeof AppProjectsIdEditRoute
  AppProjectsIdFundsRoute: typeof AppProjectsIdFundsRouteWithChildren
  AppProjectsIdReportsRoute: typeof AppProjectsIdReportsRouteWithChildren
  AppProjectsIdTasksRoute: typeof AppProjectsIdTasksRouteWithChildren
  AppProjectsIdTriggersRoute: typeof AppProjectsIdTriggersRouteWithChildren
  AppProjectsIdIndexRoute: typeof AppProjectsIdIndexRoute
  AppProjectsIdCommunicationCampaignIdRoute: typeof AppProjectsIdCommunicationCampaignIdRoute
  AppProjectsIdCommunicationAddRoute: typeof AppProjectsIdCommunicationAddRoute
  AppProjectsIdCommunicationIndexRoute: typeof AppProjectsIdCommunicationIndexRoute
}

const AppProjectsIdRouteChildren: AppProjectsIdRouteChildren = {
  AppProjectsIdBeneficiariesRoute: AppProjectsIdBeneficiariesRouteWithChildren,
  AppProjectsIdBenefitsRoute: AppProjectsIdBenefitsRouteWithChildren,
  AppProjectsIdEditRoute: AppProjectsIdEditRoute,
  AppProjectsIdFundsRoute: AppProjectsIdFundsRouteWithChildren,
  AppProjectsIdReportsRoute: AppProjectsIdReportsRouteWithChildren,
  AppProjectsIdTasksRoute: AppProjectsIdTasksRouteWithChildren,
  AppProjectsIdTriggersRoute: AppProjectsIdTriggersRouteWithChildren,
  AppProjectsIdIndexRoute: AppProjectsIdIndexRoute,
  AppProjectsIdCommunicationCampaignIdRoute:
    AppProjectsIdCommunicationCampaignIdRoute,
  AppProjectsIdCommunicationAddRoute: AppProjectsIdCommunicationAddRoute,
  AppProjectsIdCommunicationIndexRoute: AppProjectsIdCommunicationIndexRoute,
}

const AppProjectsIdRouteWithChildren = AppProjectsIdRoute._addFileChildren(
  AppProjectsIdRouteChildren,
)

interface AppProjectsRouteChildren {
  AppProjectsIdRoute: typeof AppProjectsIdRouteWithChildren
  AppProjectsNewRoute: typeof AppProjectsNewRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
}

const AppProjectsRouteChildren: AppProjectsRouteChildren = {
  AppProjectsIdRoute: AppProjectsIdRouteWithChildren,
  AppProjectsNewRoute: AppProjectsNewRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
}

const AppProjectsRouteWithChildren = AppProjectsRoute._addFileChildren(
  AppProjectsRouteChildren,
)

interface AppReportsRouteChildren {
  AppReportsIndexRoute: typeof AppReportsIndexRoute
}

const AppReportsRouteChildren: AppReportsRouteChildren = {
  AppReportsIndexRoute: AppReportsIndexRoute,
}

const AppReportsRouteWithChildren = AppReportsRoute._addFileChildren(
  AppReportsRouteChildren,
)

interface AppServicesRouteChildren {
  AppServicesAddRoute: typeof AppServicesAddRoute
  AppServicesIndexRoute: typeof AppServicesIndexRoute
  AppServicesServiceIdEditRoute: typeof AppServicesServiceIdEditRoute
}

const AppServicesRouteChildren: AppServicesRouteChildren = {
  AppServicesAddRoute: AppServicesAddRoute,
  AppServicesIndexRoute: AppServicesIndexRoute,
  AppServicesServiceIdEditRoute: AppServicesServiceIdEditRoute,
}

const AppServicesRouteWithChildren = AppServicesRoute._addFileChildren(
  AppServicesRouteChildren,
)

interface AppUsersRouteChildren {
  AppUsersAddRoute: typeof AppUsersAddRoute
  AppUsersIndexRoute: typeof AppUsersIndexRoute
  AppUsersUserIdEditRoute: typeof AppUsersUserIdEditRoute
}

const AppUsersRouteChildren: AppUsersRouteChildren = {
  AppUsersAddRoute: AppUsersAddRoute,
  AppUsersIndexRoute: AppUsersIndexRoute,
  AppUsersUserIdEditRoute: AppUsersUserIdEditRoute,
}

const AppUsersRouteWithChildren = AppUsersRoute._addFileChildren(
  AppUsersRouteChildren,
)

interface AppVendorsVendorIdRouteChildren {
  AppVendorsVendorIdEditRoute: typeof AppVendorsVendorIdEditRoute
  AppVendorsVendorIdIndexRoute: typeof AppVendorsVendorIdIndexRoute
}

const AppVendorsVendorIdRouteChildren: AppVendorsVendorIdRouteChildren = {
  AppVendorsVendorIdEditRoute: AppVendorsVendorIdEditRoute,
  AppVendorsVendorIdIndexRoute: AppVendorsVendorIdIndexRoute,
}

const AppVendorsVendorIdRouteWithChildren =
  AppVendorsVendorIdRoute._addFileChildren(AppVendorsVendorIdRouteChildren)

interface AppVendorsRouteChildren {
  AppVendorsVendorIdRoute: typeof AppVendorsVendorIdRouteWithChildren
  AppVendorsAddRoute: typeof AppVendorsAddRoute
  AppVendorsIndexRoute: typeof AppVendorsIndexRoute
}

const AppVendorsRouteChildren: AppVendorsRouteChildren = {
  AppVendorsVendorIdRoute: AppVendorsVendorIdRouteWithChildren,
  AppVendorsAddRoute: AppVendorsAddRoute,
  AppVendorsIndexRoute: AppVendorsIndexRoute,
}

const AppVendorsRouteWithChildren = AppVendorsRoute._addFileChildren(
  AppVendorsRouteChildren,
)

interface AppRouteChildren {
  AppForecastRoute: typeof AppForecastRouteWithChildren
  AppFundsRoute: typeof AppFundsRouteWithChildren
  AppPluginsRoute: typeof AppPluginsRoute
  AppProjectsRoute: typeof AppProjectsRouteWithChildren
  AppReportsRoute: typeof AppReportsRouteWithChildren
  AppServicesRoute: typeof AppServicesRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppUsersRoute: typeof AppUsersRouteWithChildren
  AppVendorsRoute: typeof AppVendorsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppForecastRoute: AppForecastRouteWithChildren,
  AppFundsRoute: AppFundsRouteWithChildren,
  AppPluginsRoute: AppPluginsRoute,
  AppProjectsRoute: AppProjectsRouteWithChildren,
  AppReportsRoute: AppReportsRouteWithChildren,
  AppServicesRoute: AppServicesRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppUsersRoute: AppUsersRouteWithChildren,
  AppVendorsRoute: AppVendorsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
