/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppVendorsRouteImport } from './routes/_app.vendors'
import { Route as AppUsersRouteImport } from './routes/_app.users'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppServicesRouteImport } from './routes/_app.services'
import { Route as AppProjectsRouteImport } from './routes/_app.projects'
import { Route as AppFundManagementRouteImport } from './routes/_app.fund-management'
import { Route as AppProjectsIndexRouteImport } from './routes/_app.projects.index'
import { Route as AppProjectsNewRouteImport } from './routes/_app.projects.new'
import { Route as AppProjectsIdRouteImport } from './routes/_app.projects.$id'
import { Route as AppProjectsIdIndexRouteImport } from './routes/_app.projects.$id.index'
import { Route as AppProjectsIdProjectManagementRouteImport } from './routes/_app.projects.$id.project-management'
import { Route as AppProjectsIdBenefitsRouteImport } from './routes/_app.projects.$id.benefits'
import { Route as AppProjectsIdBeneficiariesRouteImport } from './routes/_app.projects.$id.beneficiaries'
import { Route as AppProjectsIdProjectManagementAddTaskRouteImport } from './routes/_app.projects.$id.project-management.add-task'
import { Route as AppProjectsIdBenefitsTokensRouteImport } from './routes/_app.projects.$id.benefits.tokens'
import { Route as AppProjectsIdBeneficiariesGroupsRouteImport } from './routes/_app.projects.$id.beneficiaries.groups'
import { Route as AppProjectsIdBeneficiariesAddRouteImport } from './routes/_app.projects.$id.beneficiaries.add'
import { Route as AppProjectsIdBeneficiariesBeneficiaryIdEditRouteImport } from './routes/_app.projects.$id.beneficiaries.$beneficiaryId.edit'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppVendorsRoute = AppVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppServicesRoute = AppServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppFundManagementRoute = AppFundManagementRouteImport.update({
  id: '/fund-management',
  path: '/fund-management',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProjectsRoute,
} as any)
const AppProjectsNewRoute = AppProjectsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppProjectsRoute,
} as any)
const AppProjectsIdRoute = AppProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppProjectsRoute,
} as any)
const AppProjectsIdIndexRoute = AppProjectsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProjectsIdRoute,
} as any)
const AppProjectsIdProjectManagementRoute =
  AppProjectsIdProjectManagementRouteImport.update({
    id: '/project-management',
    path: '/project-management',
    getParentRoute: () => AppProjectsIdRoute,
  } as any)
const AppProjectsIdBenefitsRoute = AppProjectsIdBenefitsRouteImport.update({
  id: '/benefits',
  path: '/benefits',
  getParentRoute: () => AppProjectsIdRoute,
} as any)
const AppProjectsIdBeneficiariesRoute =
  AppProjectsIdBeneficiariesRouteImport.update({
    id: '/beneficiaries',
    path: '/beneficiaries',
    getParentRoute: () => AppProjectsIdRoute,
  } as any)
const AppProjectsIdProjectManagementAddTaskRoute =
  AppProjectsIdProjectManagementAddTaskRouteImport.update({
    id: '/add-task',
    path: '/add-task',
    getParentRoute: () => AppProjectsIdProjectManagementRoute,
  } as any)
const AppProjectsIdBenefitsTokensRoute =
  AppProjectsIdBenefitsTokensRouteImport.update({
    id: '/tokens',
    path: '/tokens',
    getParentRoute: () => AppProjectsIdBenefitsRoute,
  } as any)
const AppProjectsIdBeneficiariesGroupsRoute =
  AppProjectsIdBeneficiariesGroupsRouteImport.update({
    id: '/groups',
    path: '/groups',
    getParentRoute: () => AppProjectsIdBeneficiariesRoute,
  } as any)
const AppProjectsIdBeneficiariesAddRoute =
  AppProjectsIdBeneficiariesAddRouteImport.update({
    id: '/add',
    path: '/add',
    getParentRoute: () => AppProjectsIdBeneficiariesRoute,
  } as any)
const AppProjectsIdBeneficiariesBeneficiaryIdEditRoute =
  AppProjectsIdBeneficiariesBeneficiaryIdEditRouteImport.update({
    id: '/$beneficiaryId/edit',
    path: '/$beneficiaryId/edit',
    getParentRoute: () => AppProjectsIdBeneficiariesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/fund-management': typeof AppFundManagementRoute
  '/projects': typeof AppProjectsRouteWithChildren
  '/services': typeof AppServicesRoute
  '/settings': typeof AppSettingsRoute
  '/users': typeof AppUsersRoute
  '/vendors': typeof AppVendorsRoute
  '/projects/$id': typeof AppProjectsIdRouteWithChildren
  '/projects/new': typeof AppProjectsNewRoute
  '/projects/': typeof AppProjectsIndexRoute
  '/projects/$id/beneficiaries': typeof AppProjectsIdBeneficiariesRouteWithChildren
  '/projects/$id/benefits': typeof AppProjectsIdBenefitsRouteWithChildren
  '/projects/$id/project-management': typeof AppProjectsIdProjectManagementRouteWithChildren
  '/projects/$id/': typeof AppProjectsIdIndexRoute
  '/projects/$id/beneficiaries/add': typeof AppProjectsIdBeneficiariesAddRoute
  '/projects/$id/beneficiaries/groups': typeof AppProjectsIdBeneficiariesGroupsRoute
  '/projects/$id/benefits/tokens': typeof AppProjectsIdBenefitsTokensRoute
  '/projects/$id/project-management/add-task': typeof AppProjectsIdProjectManagementAddTaskRoute
  '/projects/$id/beneficiaries/$beneficiaryId/edit': typeof AppProjectsIdBeneficiariesBeneficiaryIdEditRoute
}
export interface FileRoutesByTo {
  '/fund-management': typeof AppFundManagementRoute
  '/services': typeof AppServicesRoute
  '/settings': typeof AppSettingsRoute
  '/users': typeof AppUsersRoute
  '/vendors': typeof AppVendorsRoute
  '/': typeof AppIndexRoute
  '/projects/new': typeof AppProjectsNewRoute
  '/projects': typeof AppProjectsIndexRoute
  '/projects/$id/beneficiaries': typeof AppProjectsIdBeneficiariesRouteWithChildren
  '/projects/$id/benefits': typeof AppProjectsIdBenefitsRouteWithChildren
  '/projects/$id/project-management': typeof AppProjectsIdProjectManagementRouteWithChildren
  '/projects/$id': typeof AppProjectsIdIndexRoute
  '/projects/$id/beneficiaries/add': typeof AppProjectsIdBeneficiariesAddRoute
  '/projects/$id/beneficiaries/groups': typeof AppProjectsIdBeneficiariesGroupsRoute
  '/projects/$id/benefits/tokens': typeof AppProjectsIdBenefitsTokensRoute
  '/projects/$id/project-management/add-task': typeof AppProjectsIdProjectManagementAddTaskRoute
  '/projects/$id/beneficiaries/$beneficiaryId/edit': typeof AppProjectsIdBeneficiariesBeneficiaryIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/fund-management': typeof AppFundManagementRoute
  '/_app/projects': typeof AppProjectsRouteWithChildren
  '/_app/services': typeof AppServicesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/vendors': typeof AppVendorsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/projects/$id': typeof AppProjectsIdRouteWithChildren
  '/_app/projects/new': typeof AppProjectsNewRoute
  '/_app/projects/': typeof AppProjectsIndexRoute
  '/_app/projects/$id/beneficiaries': typeof AppProjectsIdBeneficiariesRouteWithChildren
  '/_app/projects/$id/benefits': typeof AppProjectsIdBenefitsRouteWithChildren
  '/_app/projects/$id/project-management': typeof AppProjectsIdProjectManagementRouteWithChildren
  '/_app/projects/$id/': typeof AppProjectsIdIndexRoute
  '/_app/projects/$id/beneficiaries/add': typeof AppProjectsIdBeneficiariesAddRoute
  '/_app/projects/$id/beneficiaries/groups': typeof AppProjectsIdBeneficiariesGroupsRoute
  '/_app/projects/$id/benefits/tokens': typeof AppProjectsIdBenefitsTokensRoute
  '/_app/projects/$id/project-management/add-task': typeof AppProjectsIdProjectManagementAddTaskRoute
  '/_app/projects/$id/beneficiaries/$beneficiaryId/edit': typeof AppProjectsIdBeneficiariesBeneficiaryIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/fund-management'
    | '/projects'
    | '/services'
    | '/settings'
    | '/users'
    | '/vendors'
    | '/projects/$id'
    | '/projects/new'
    | '/projects/'
    | '/projects/$id/beneficiaries'
    | '/projects/$id/benefits'
    | '/projects/$id/project-management'
    | '/projects/$id/'
    | '/projects/$id/beneficiaries/add'
    | '/projects/$id/beneficiaries/groups'
    | '/projects/$id/benefits/tokens'
    | '/projects/$id/project-management/add-task'
    | '/projects/$id/beneficiaries/$beneficiaryId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/fund-management'
    | '/services'
    | '/settings'
    | '/users'
    | '/vendors'
    | '/'
    | '/projects/new'
    | '/projects'
    | '/projects/$id/beneficiaries'
    | '/projects/$id/benefits'
    | '/projects/$id/project-management'
    | '/projects/$id'
    | '/projects/$id/beneficiaries/add'
    | '/projects/$id/beneficiaries/groups'
    | '/projects/$id/benefits/tokens'
    | '/projects/$id/project-management/add-task'
    | '/projects/$id/beneficiaries/$beneficiaryId/edit'
  id:
    | '__root__'
    | '/_app'
    | '/_app/fund-management'
    | '/_app/projects'
    | '/_app/services'
    | '/_app/settings'
    | '/_app/users'
    | '/_app/vendors'
    | '/_app/'
    | '/_app/projects/$id'
    | '/_app/projects/new'
    | '/_app/projects/'
    | '/_app/projects/$id/beneficiaries'
    | '/_app/projects/$id/benefits'
    | '/_app/projects/$id/project-management'
    | '/_app/projects/$id/'
    | '/_app/projects/$id/beneficiaries/add'
    | '/_app/projects/$id/beneficiaries/groups'
    | '/_app/projects/$id/benefits/tokens'
    | '/_app/projects/$id/project-management/add-task'
    | '/_app/projects/$id/beneficiaries/$beneficiaryId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vendors': {
      id: '/_app/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof AppVendorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/services': {
      id: '/_app/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof AppServicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects': {
      id: '/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fund-management': {
      id: '/_app/fund-management'
      path: '/fund-management'
      fullPath: '/fund-management'
      preLoaderRoute: typeof AppFundManagementRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/': {
      id: '/_app/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/_app/projects/new': {
      id: '/_app/projects/new'
      path: '/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof AppProjectsNewRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/_app/projects/$id': {
      id: '/_app/projects/$id'
      path: '/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof AppProjectsIdRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/_app/projects/$id/': {
      id: '/_app/projects/$id/'
      path: '/'
      fullPath: '/projects/$id/'
      preLoaderRoute: typeof AppProjectsIdIndexRouteImport
      parentRoute: typeof AppProjectsIdRoute
    }
    '/_app/projects/$id/project-management': {
      id: '/_app/projects/$id/project-management'
      path: '/project-management'
      fullPath: '/projects/$id/project-management'
      preLoaderRoute: typeof AppProjectsIdProjectManagementRouteImport
      parentRoute: typeof AppProjectsIdRoute
    }
    '/_app/projects/$id/benefits': {
      id: '/_app/projects/$id/benefits'
      path: '/benefits'
      fullPath: '/projects/$id/benefits'
      preLoaderRoute: typeof AppProjectsIdBenefitsRouteImport
      parentRoute: typeof AppProjectsIdRoute
    }
    '/_app/projects/$id/beneficiaries': {
      id: '/_app/projects/$id/beneficiaries'
      path: '/beneficiaries'
      fullPath: '/projects/$id/beneficiaries'
      preLoaderRoute: typeof AppProjectsIdBeneficiariesRouteImport
      parentRoute: typeof AppProjectsIdRoute
    }
    '/_app/projects/$id/project-management/add-task': {
      id: '/_app/projects/$id/project-management/add-task'
      path: '/add-task'
      fullPath: '/projects/$id/project-management/add-task'
      preLoaderRoute: typeof AppProjectsIdProjectManagementAddTaskRouteImport
      parentRoute: typeof AppProjectsIdProjectManagementRoute
    }
    '/_app/projects/$id/benefits/tokens': {
      id: '/_app/projects/$id/benefits/tokens'
      path: '/tokens'
      fullPath: '/projects/$id/benefits/tokens'
      preLoaderRoute: typeof AppProjectsIdBenefitsTokensRouteImport
      parentRoute: typeof AppProjectsIdBenefitsRoute
    }
    '/_app/projects/$id/beneficiaries/groups': {
      id: '/_app/projects/$id/beneficiaries/groups'
      path: '/groups'
      fullPath: '/projects/$id/beneficiaries/groups'
      preLoaderRoute: typeof AppProjectsIdBeneficiariesGroupsRouteImport
      parentRoute: typeof AppProjectsIdBeneficiariesRoute
    }
    '/_app/projects/$id/beneficiaries/add': {
      id: '/_app/projects/$id/beneficiaries/add'
      path: '/add'
      fullPath: '/projects/$id/beneficiaries/add'
      preLoaderRoute: typeof AppProjectsIdBeneficiariesAddRouteImport
      parentRoute: typeof AppProjectsIdBeneficiariesRoute
    }
    '/_app/projects/$id/beneficiaries/$beneficiaryId/edit': {
      id: '/_app/projects/$id/beneficiaries/$beneficiaryId/edit'
      path: '/$beneficiaryId/edit'
      fullPath: '/projects/$id/beneficiaries/$beneficiaryId/edit'
      preLoaderRoute: typeof AppProjectsIdBeneficiariesBeneficiaryIdEditRouteImport
      parentRoute: typeof AppProjectsIdBeneficiariesRoute
    }
  }
}

interface AppProjectsIdBeneficiariesRouteChildren {
  AppProjectsIdBeneficiariesAddRoute: typeof AppProjectsIdBeneficiariesAddRoute
  AppProjectsIdBeneficiariesGroupsRoute: typeof AppProjectsIdBeneficiariesGroupsRoute
  AppProjectsIdBeneficiariesBeneficiaryIdEditRoute: typeof AppProjectsIdBeneficiariesBeneficiaryIdEditRoute
}

const AppProjectsIdBeneficiariesRouteChildren: AppProjectsIdBeneficiariesRouteChildren =
  {
    AppProjectsIdBeneficiariesAddRoute: AppProjectsIdBeneficiariesAddRoute,
    AppProjectsIdBeneficiariesGroupsRoute:
      AppProjectsIdBeneficiariesGroupsRoute,
    AppProjectsIdBeneficiariesBeneficiaryIdEditRoute:
      AppProjectsIdBeneficiariesBeneficiaryIdEditRoute,
  }

const AppProjectsIdBeneficiariesRouteWithChildren =
  AppProjectsIdBeneficiariesRoute._addFileChildren(
    AppProjectsIdBeneficiariesRouteChildren,
  )

interface AppProjectsIdBenefitsRouteChildren {
  AppProjectsIdBenefitsTokensRoute: typeof AppProjectsIdBenefitsTokensRoute
}

const AppProjectsIdBenefitsRouteChildren: AppProjectsIdBenefitsRouteChildren = {
  AppProjectsIdBenefitsTokensRoute: AppProjectsIdBenefitsTokensRoute,
}

const AppProjectsIdBenefitsRouteWithChildren =
  AppProjectsIdBenefitsRoute._addFileChildren(
    AppProjectsIdBenefitsRouteChildren,
  )

interface AppProjectsIdProjectManagementRouteChildren {
  AppProjectsIdProjectManagementAddTaskRoute: typeof AppProjectsIdProjectManagementAddTaskRoute
}

const AppProjectsIdProjectManagementRouteChildren: AppProjectsIdProjectManagementRouteChildren =
  {
    AppProjectsIdProjectManagementAddTaskRoute:
      AppProjectsIdProjectManagementAddTaskRoute,
  }

const AppProjectsIdProjectManagementRouteWithChildren =
  AppProjectsIdProjectManagementRoute._addFileChildren(
    AppProjectsIdProjectManagementRouteChildren,
  )

interface AppProjectsIdRouteChildren {
  AppProjectsIdBeneficiariesRoute: typeof AppProjectsIdBeneficiariesRouteWithChildren
  AppProjectsIdBenefitsRoute: typeof AppProjectsIdBenefitsRouteWithChildren
  AppProjectsIdProjectManagementRoute: typeof AppProjectsIdProjectManagementRouteWithChildren
  AppProjectsIdIndexRoute: typeof AppProjectsIdIndexRoute
}

const AppProjectsIdRouteChildren: AppProjectsIdRouteChildren = {
  AppProjectsIdBeneficiariesRoute: AppProjectsIdBeneficiariesRouteWithChildren,
  AppProjectsIdBenefitsRoute: AppProjectsIdBenefitsRouteWithChildren,
  AppProjectsIdProjectManagementRoute:
    AppProjectsIdProjectManagementRouteWithChildren,
  AppProjectsIdIndexRoute: AppProjectsIdIndexRoute,
}

const AppProjectsIdRouteWithChildren = AppProjectsIdRoute._addFileChildren(
  AppProjectsIdRouteChildren,
)

interface AppProjectsRouteChildren {
  AppProjectsIdRoute: typeof AppProjectsIdRouteWithChildren
  AppProjectsNewRoute: typeof AppProjectsNewRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
}

const AppProjectsRouteChildren: AppProjectsRouteChildren = {
  AppProjectsIdRoute: AppProjectsIdRouteWithChildren,
  AppProjectsNewRoute: AppProjectsNewRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
}

const AppProjectsRouteWithChildren = AppProjectsRoute._addFileChildren(
  AppProjectsRouteChildren,
)

interface AppRouteChildren {
  AppFundManagementRoute: typeof AppFundManagementRoute
  AppProjectsRoute: typeof AppProjectsRouteWithChildren
  AppServicesRoute: typeof AppServicesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppUsersRoute: typeof AppUsersRoute
  AppVendorsRoute: typeof AppVendorsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppFundManagementRoute: AppFundManagementRoute,
  AppProjectsRoute: AppProjectsRouteWithChildren,
  AppServicesRoute: AppServicesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppUsersRoute: AppUsersRoute,
  AppVendorsRoute: AppVendorsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
