/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppVendorsRouteImport } from './routes/_app.vendors'
import { Route as AppUsersRouteImport } from './routes/_app.users'
import { Route as AppServicesRouteImport } from './routes/_app.services'
import { Route as AppProjectsRouteImport } from './routes/_app.projects'
import { Route as AppFundManagementRouteImport } from './routes/_app.fund-management'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppVendorsRoute = AppVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppServicesRoute = AppServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppFundManagementRoute = AppFundManagementRouteImport.update({
  id: '/fund-management',
  path: '/fund-management',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/fund-management': typeof AppFundManagementRoute
  '/projects': typeof AppProjectsRoute
  '/services': typeof AppServicesRoute
  '/users': typeof AppUsersRoute
  '/vendors': typeof AppVendorsRoute
}
export interface FileRoutesByTo {
  '/fund-management': typeof AppFundManagementRoute
  '/projects': typeof AppProjectsRoute
  '/services': typeof AppServicesRoute
  '/users': typeof AppUsersRoute
  '/vendors': typeof AppVendorsRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/fund-management': typeof AppFundManagementRoute
  '/_app/projects': typeof AppProjectsRoute
  '/_app/services': typeof AppServicesRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/vendors': typeof AppVendorsRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/fund-management'
    | '/projects'
    | '/services'
    | '/users'
    | '/vendors'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/fund-management'
    | '/projects'
    | '/services'
    | '/users'
    | '/vendors'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/_app/fund-management'
    | '/_app/projects'
    | '/_app/services'
    | '/_app/users'
    | '/_app/vendors'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vendors': {
      id: '/_app/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof AppVendorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/services': {
      id: '/_app/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof AppServicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects': {
      id: '/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fund-management': {
      id: '/_app/fund-management'
      path: '/fund-management'
      fullPath: '/fund-management'
      preLoaderRoute: typeof AppFundManagementRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppFundManagementRoute: typeof AppFundManagementRoute
  AppProjectsRoute: typeof AppProjectsRoute
  AppServicesRoute: typeof AppServicesRoute
  AppUsersRoute: typeof AppUsersRoute
  AppVendorsRoute: typeof AppVendorsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppFundManagementRoute: AppFundManagementRoute,
  AppProjectsRoute: AppProjectsRoute,
  AppServicesRoute: AppServicesRoute,
  AppUsersRoute: AppUsersRoute,
  AppVendorsRoute: AppVendorsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
